<?php
//INSTACIA AS CLASSES
$artigoController = new ArtigoController();
$artigo = new Artigo();
$helper = new Helper();
$upload = new Upload();
$resultado = "";

//ALTERAR IMAGEM DO PROJETO
$submitImage = filter_input(INPUT_POST, 'submitImage', FILTER_SANITIZE_STRING);
if ($submitImage):
    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);

    $retornaImagem = $artigoController->retornaArtigoImagem($cod);
    $thumbArtigo = $retornaImagem->getThumb();
    $nomeArtigo = $retornaImagem->getTitulo();
    $capa = "../upload/" . $thumbArtigo;
    if (file_exists($capa) && !is_dir($capa)):
        unlink($capa);
    endif;
    //imagem esta recebendo files imagemArtigo
    $imagem = $_FILES['imagemArtigo'];
    //recebendo a imagem, nome do artigo, tamanho da imagem, pasta
    $upload->Image($imagem, $nomeArtigo, 1000, 'artigo');
    //setando a imagem
    $nomeImagem = $upload->getResult();
    $artigo->setThumb($nomeArtigo);

    if ($artigoController->AlterarImagem($cod, $nomeImagem)):
        $insertGoTo = '?pagina=listarArtigo';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-success\">A imagem <b>{$nomeArtigo} </b> foi alterado com sucesso</div>";
    else:
        $insertGoTo = '?pagina=artigo';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-danger\">Erro ao alterar </div>";
    endif;
endif;

//ALTERA O ARTIGO                            
$btnAtualizar = filter_input(INPUT_POST, 'btnAtualizar', FILTER_SANITIZE_STRING);
if ($btnAtualizar):

    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
    $artigo->setCod($cod);
    $artigo->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
    $url = $helper->Name($artigo->getTitulo());
    $artigo->setUrl($url);
    $artigo->setAutor(filter_input(INPUT_POST, 'txtAutor', FILTER_SANITIZE_STRING));
    $artigo->setDescrever_imagem(filter_input(INPUT_POST, 'txtBdescricao', FILTER_SANITIZE_STRING));
    $artigo->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
    $artigo->setSugerido(filter_input(INPUT_POST, 'slSugerir', FILTER_SANITIZE_NUMBER_INT));
    $artigo->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_FULL_SPECIAL_CHARS));
    $artigo->setData(date('Y-m-d H:i:s'));
    //CCONDICAO PARA ALTERAR O ARTIGO
    if ($artigoController->Atualizar($artigo)):
        $insertGoTo = '?pagina=listarArtigo';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-success">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Atualizado efetuado com sucesso - </b></span>
                    </div>';
    else:
        $insertGoTo = '?pagina=editarArtigo';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-danger">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Erro ao Atualizar - Favor preencha todos os campos</b></span>
                    </div>';
    endif;
endif;

//RETORNA DADOS PARA O FORMULARIO
$cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
$retornarArtigo = $artigoController->retornaIdArtigo($cod);
if ($retornarArtigo == NULL):
else:
    $nome = $retornarArtigo->getTitulo();
    $autor = $retornarArtigo->getAutor();
    $descricao = $retornarArtigo->getDescricao();
    $thumb = $retornarArtigo->getThumb();
    $descricao_img = $retornarArtigo->getDescrever_imagem();
    $status = $retornarArtigo->getStatus();
    $sugestao = $retornarArtigo->getSugerido();
    ?>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="?pagina=listarArtigo">PAGE BLOG</a>
                </div>
                <?php require_once './inc/header_top.php'; ?>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">

                    <form method="post" enctype="multipart/form-data">
                        <div class="col-lg-8 col-md-7">
                            <div class="card">
                                <div class="header">
                                    <h4 class="title"Atualizar Artigo</h4>
                                </div>
                                <div class="content">
                                    <form method="post" enctype="multipart/form-data" id="frmCategoria" name="frmCategoria" novalidate onSubmit="return validaCadastro();" >

                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="txtTitulo">Titulo</label>
                                                    <input type="text" name="txtTitulo" id="txtTitulo" class="form-control border-input" placeholder="Titulo para o artigo" value="<?= $nome; ?>">
                                                    <span class="msg-error msg-titulo"></span>
                                                </div>
                                            </div>                                    
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="txtAutor">Autor</label>
                                                    <input type="text" name="txtAutor" id="txtAutor" class="form-control border-input" placeholder="Nome do Autor"  value="<?= $autor; ?>">
                                                    <span class="msg-error msg-titulo"></span>
                                                </div>
                                            </div>  
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="txtBdescricao">Descrição rodapé da Imagem</label>
                                                    <input type="text" name="txtBdescricao" id="txtBdescricao" class="form-control border-input" placeholder="Breve descrição para imagem"  value="<?= $descricao_img; ?>">
                                                    <span class="msg-error msg-titulo"></span>
                                                </div>
                                            </div>  

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="slSugerir">Sugerir Artigo</label>
                                                    <select name="slSugerir" id="slSugerir" class="form-control border-input">
                                                        <?php
                                                        if ($sugestao == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Sugerir</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="0" selected='selected'>Não Sugerir</option>
                                                        <?php
                                                        endif;
                                                        if ($sugestao != 1):
                                                            ?>
                                                            <option value="1" <?php $sugestao == 1 ? "selected='selected'" : "" ?>>Sugerir</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="0" <?php $sugestao == 0 ? "selected='selected'" : "" ?>>Não Sugerir</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div> 

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="slStatus">Status</label>
                                                    <select name="slStatus" id="slStatus" class="form-control border-input">
                                                        <?php
                                                        if ($status == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        if ($status != 1):
                                                            ?>
                                                            <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div> 

                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="txtDescricao">Descrição do Artigo</label>
                                                    <textarea rows="3" name="txtDescricao" class="form-control border-input">
                                                        <?= $descricao; ?>
                                                    </textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <?= $resultado; ?>
                                            </div>


                                        </div>                                    

                                        <div class="text-center">
                                            <input type="submit" class="btn btn-info btn-fill btn-wd" name="btnAtualizar" value="Atualizar Artigo"/>
                                        </div>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="col-lg-4 col-md-5">
                        <div class="card card-user">
                            <div class="image">
                                <?php
                                if ($thumb == null):
                                    echo '<img id="img-uploaded" src="assets/img/no_image.jpg" alt="Sua imagem">';
                                else:
                                    echo "<img id='img-uploaded' src='../upload/{$thumb}' alt='Sua imagem'>";
                                endif;
                                ?>
                            </div>                        
                        </div>
                        <div class="card">
                            <div class="row" id="image_preview">                               
                            </div>
                            <div class="content">                            
                                <div class="row">                                 
                                    <form action="" method="post" enctype="multipart/form-data">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>CAPA (JPG 800X400PX):</label>
                                                <input type="file" class="form-control border-input uploader" id="imagemArtigo"  name="imagemArtigo">
                                            </div>
                                        </div>
                                        <div class="col-md-12 text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name='submitImage' value="AlterarCapa"/>
                                        </div>
                                    </form>                              
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
endif;
?>
<script type="text/javascript">
    function preview_images()
    {
        var total_file = document.getElementById("images").files.length;
        for (var i = 0; i < total_file; i++)
        {
            $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
        }
    }
</script>