<?php
//instanciando as classes
$portfolioController = new PortfolioController();
$portfolio = new Portifolio();
$helper = new Helper();
$upload = new Upload();

$resultado = "";


//ALTERAR IMAGEM DO PROJETO
$submitImage = filter_input(INPUT_POST, 'submitImage', FILTER_SANITIZE_STRING);
if ($submitImage):
    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);

    $retornaImagem = $portfolioController->retornaPortfolioImagem($cod);
    $thumbProjeto = $retornaImagem->getThumb();
    $nomeProjeto = $retornaImagem->getTitulo();

    $capa = "../upload/" . $thumbProjeto;
    if (file_exists($capa) && !is_dir($capa)):
        unlink($capa);
    endif;
    //imagem esta recebendo files imagemArtigo
    $imagem = $_FILES['imagemArtigo'];
    //recebendo a imagem, nome do projeto, tamanho da imagem, pasta
    $upload->Image($imagem, $nomeProjeto, 1000, 'portfolio');
    //setando a imagem
    $nomeImagem = $upload->getResult();
    $portfolio->setThumb($nomeImagem);

    if ($portfolioController->AlterarImagem($cod, $nomeImagem)):
        $insertGoTo = '?pagina=listarPortifolio';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-success\">A imagem <b>{$nomeImagem} </b> foi alterado com sucesso</div>";
    else:
        $insertGoTo = '?pagina=portifolio';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-danger\">Erro ao alterar </div>";
    endif;
endif;

//ALTERA O PROJETO                            
$btnAlterar = filter_input(INPUT_POST, 'btnAlterar', FILTER_SANITIZE_STRING);
if ($btnAlterar):

    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
    $portfolio->setCod($cod);
    $portfolio->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
    $url = $helper->Name($portfolio->getTitulo());
    $portfolio->setUrl($url);
    $portfolio->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
    $portfolio->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_SPECIAL_CHARS));
    $portfolio->setData(date('Y-m-d H:i:s'));
    //CCONDICAO PARA ALTERAR O PROJETO
    if ($portfolioController->Atualizar($portfolio)):
        $insertGoTo = '?pagina=listarPortifolio';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-success">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Atualizado efetuado com sucesso - </b></span>
                    </div>';
    else:
        $insertGoTo = '?pagina=editarPortifolio';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-danger">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Erro ao Atualizar - Favor preencha todos os campos</b></span>
                    </div>';
    endif;
endif;

//RETORNA DADOS PARA O FORMULARIO
$cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
$retornaProjeto = $portfolioController->retornaIdProjeto($cod);
if ($retornaProjeto == NULL):
else:
    $nome = $retornaProjeto->getTitulo();
    $descricao = $retornaProjeto->getDescricao();
    $thumb = $retornaProjeto->getThumb();
    $status = $retornaProjeto->getStatus();
    ?>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="?pagina=listarPortifólio">PAGE PORTIFÓLIO</a>
                </div>
                <?php require_once './inc/header_top.php'; ?>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">

                    <form method="post" enctype="multipart/form-data">
                        <div class="col-lg-8 col-md-7">
                            <div class="card">
                                <div class="header">
                                    <h4 class="title">Atualizar Portifólio</h4>
                                </div>

                                <div class="content">

                                    <form method="post" enctype="multipart/form-data" id="frmCategoria" name="frmCategoria" novalidate onSubmit="return validaCadastro();" >
                                        
                                        <div class="row">
                                            <div class="col-md-8">
                                                <div class="form-group">
                                                    <label>Portifólio</label>
                                                    <input type="text" name="txtTitulo" id="txtTitulo" class="form-control border-input" value="<?= $nome; ?>">
                                                    <span class="msg-error msg-titulo"></span>
                                                </div>
                                            </div> 

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slStatus">Status</label>
                                                    <select name="slStatus" id="slStatus" class="form-control border-input">
                                                        <?php
                                                        if ($status == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        if ($status != 1):
                                                            ?>
                                                            <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>

                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Descrição do Portifólio</label>
                                                    <textarea rows="3" name="txtDescricao" class="form-control border-input">
                                                        <?= $descricao; ?>
                                                    </textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <?= $resultado; ?>
                                            </div>
                                        </div>                                    

                                        <div class="text-center">
                                            <input type="submit" class="btn btn-info btn-fill btn-wd" name="btnAlterar" value="Atualizar Portifólio"/>
                                        </div>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="col-lg-4 col-md-5">
                        <div class="card card-user">
                            <div class="image">
                                <?php
                                if ($thumb == null):
                                    echo '<img id="img-uploaded" src="assets/img/no_image.jpg" alt="Sua imagem">';
                                else:
                                    echo "<img id='img-uploaded' src='../upload/{$thumb}' alt='Sua imagem'>";
                                endif;
                                ?>
                            </div>                        
                        </div>
                        <div class="card">
                            <div class="row" id="image_preview">                               
                            </div>
                            <div class="content">                            
                                <div class="row">                                 
                                    <form action="" method="post" enctype="multipart/form-data">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>CAPA (JPG 800X400PX):</label>
                                                <input type="file" class="form-control border-input uploader" id="imagemArtigo"  name="imagemArtigo">
                                            </div>
                                        </div>
                                        <div class="col-md-12 text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name='submitImage' value="AlterarCapa"/>
                                        </div>
                                    </form>                              
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
endif;
?>
<script type="text/javascript">
    function preview_images()
    {
        var total_file = document.getElementById("images").files.length;
        for (var i = 0; i < total_file; i++)
        {
            $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
        }
    }
</script>