<?php


$agendamento = new Agendamento();
$agendaController = new AgendaController();
$categoriaontroller = new CategoriaController();
$pagamentoController = new TipoPagamentoController();
$helper = new Helper();
$resultado = "";
$btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);

if ($btnCadastrar) :
    $agendamento->setCategoria(filter_input(INPUT_POST, 'especialidade', FILTER_SANITIZE_NUMBER_INT));
    $agendamento->setTipopagamento(filter_input(INPUT_POST, 'pagamento', FILTER_SANITIZE_NUMBER_INT));
    $agendamento->setAgenda_nome(filter_input(INPUT_POST, 'nome', FILTER_SANITIZE_STRING));
    $agendamento->setAgenda_email(filter_input(INPUT_POST, 'email', FILTER_SANITIZE_STRING));
    $agendamento->setAgenda_telefone(filter_input(INPUT_POST, 'telefone', FILTER_SANITIZE_STRING));    
    $agendamento->setAgenda_Data(date("Y-m-d"));
    $agendamento->setAgenda_hora(filter_input(INPUT_POST, 'hora', FILTER_SANITIZE_STRING));

    if ($agendaController->Cadastrar($agendamento)):
        $resultado = '<div class="alert alert-success">                                            
        <span><b> Cadastro </b> efetuado com sucesso </span>
        </div>';
    else:
        $resultado = '<div class="alert alert-danger">                                            
        <span><b> Erro ao cadastrar - Favor preencha todos os campos</b></span>
        </div>';
        echo "Erro";
    endif;
endif;
?>
<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">PAGE AGENDAMENTO</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>

    <div class="content">
        <div class="container-fluid">
            <div class="row">              


                <div class="col-lg-12 col-md-7">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">CADASTRAR AGENDAMENTO</h4>
                        </div>
                        <div class="content">
                            <form method="post">
                                <div class="row">
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nome</label>
                                            <input type="text" name="nome" class="form-control border-input" placeholder="Nome" required="">
                                            <span class="msg-error msg-titulo"></span>
                                        </div>
                                    </div>  
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>E-mail</label>
                                            <input type="email" name="email" class="form-control border-input" placeholder="E-mail" required="">
                                            <span class="msg-error msg-titulo"></span>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nome da Especialidade</label>
                                            <select name="especialidade" id="especialidade" class="form-control border-input">
                                                <?php
                                                $especialidade = $categoriaontroller->ListarTodasCategorias();
                                               
                                                if ($especialidade == null):
                                                    echo '<option value="">Não existem categoria cadastradas</option>';
                                                else:
                                                    echo '<option value="">Selecione a especialidade</option>';
                                                endif;
                                                foreach ($especialidade as $list):
                                                    ?>
                                                    <option value="<?= $list->getCod(); ?>"><?= $list->getTitulo(); ?></option>
                                                    <?php
                                                endforeach;
                                                ?>                                             
                                            </select>
                                        </div>
                                    </div>                                    
                                                                        
                                    
                                    <div class="col-md-6">                                        
                                        <div class="form-group">                                                
                                            
                                            <label>Forma de Pagamento</label>
                                            <select name="pagamento" class="form-control border-input">

                                                <?php
                                                $tipopagamento = new TipoPagamento();
                                                $tipopagamento = $pagamentoController->ListarTipoPagamento(0, 50);
                                                var_dump($tipopagamento);
                                                if ($tipopagamento == null):
                                                    echo '<option value="">Não existem Forma de pagamento</option>';
                                                else:
                                                    echo '<option value="">PARTICULAR OU CONVÊNIO</option>';                                                
                                                
                                                foreach ($tipopagamento as $list):                                                    
                                                    ?>
                                                <option value="<?= $list->getCod(); ?>"><?= $list->getTipo_titulo(); ?></option>
                                                    <?php
                                                endforeach;
                                                endif;
                                                ?>

                                            </select>
                                        </div>
                                    </div>     
                                    
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Telefone</label>
                                            <input type="tel" name="telefone" class="form-control border-input" placeholder="Telefone" required="">
                                            <span class="msg-error msg-titulo"></span>
                                        </div>
                                    </div>                                    
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Data</label>
                                            <input type="date" name="data"  id="calendario" class="form-control border-input date" placeholder="Data" required="">
                                            <span class="msg-error msg-titulo"></span>
                                        </div>
                                    </div>                                    
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Hora</label>
                                            <input type="time" name="hora" class="form-control border-input" placeholder="Hora" required="">
                                            <span class="msg-error msg-titulo"></span>
                                        </div>
                                    </div>                                    
                                   
                                </div>



                                <div class="row">
                                    <div class="col-md-12">
                                        <?php echo $resultado; ?>
                                    </div>                                    
                                </div>   

                                <div class="text-center">
                                    <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Cadastrar">
                                    <a href="?pagina=listarAgendamento" class="btn btn-info btn-fill btn-wd">Listar Agendamento</a>
                                </div>
                                <?php ?>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script src="<?= INCLUDE_PATH; ?>/assets/js/jquery.js" type="text/javascript"></script>
<script>

</script>


