<?php
$agendamento = new Agendamento();
$agendaController = new AgendaController();
$categoriacontroller = new CategoriaController();
$pagamentoController = new TipoPagamentoController();


//RETORNAR DADOS PARA ATUALIZAR
$cod = filter_input(INPUT_GET, 'cod', FILTER_SANITIZE_NUMBER_INT);
$retornotabela = $agendaController->retornoAgendamentoCod($cod);
if ($retornotabela == NULL):

else:
    $cod = $retornotabela->getAgenda_cod();
    $nome = $retornotabela->getAgenda_nome();
    $email = $retornotabela->getAgenda_email();
    $telefone = $retornotabela->getAgenda_telefone();
    $data = $retornotabela->getAgenda_data();
    $hora = $retornotabela->getAgenda_hora();
    $catTitulo = $retornotabela->getCategoria()->getTitulo();
    $tipoNome = $retornotabela->getTipopagamento()->getTipo_titulo();
    ?>
    ?>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">PAGE AGENDAMENTO</a>
                </div>
    <?php require_once './inc/header_top.php'; ?>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row"> 
                    <div class="col-lg-12 col-md-7">
                        <div class="card bx-agendamento-cliente">
                            <div class="header">
                                <h4 class="title">INFORMAÇÃO DO CLIENTE</h4>

                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-striped config-table">
                                    <thead>
                                    <th>CÓDIGO</th>
                                    <th>PACIENTE</th>                                                                                  
                                    <th>E-MAIL</th>                                                                                  
                                    <th>TELEFONE</th>                           
                                    <th>DATA</th>
                                    <th>HORA</th>
                                    <th>PARTICULAR | CONVÊNIO</th>
                                    <th>ESPECIALIZAÇÃO</th>                                
                                    </thead>
                                    <tbody>

                                    <td><?= $cod ?></td>  
                                    <td><?= $nome ?></td>  
                                    <td><?= $email ?></td>  
                                    <td><?= $telefone ?></td>  
                                    <td><?= $data ?></td>  
                                    <td><?= $hora ?></td> 
                                    <td><?= $catTitulo; ?></td>  
                                    <td><?= $tipoNome ?></td>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
<?php
endif;
?>
<script src="<?= INCLUDE_PATH; ?>/assets/js/jquery.js" type="text/javascript"></script>
<script>

</script>


